name: stale-branches.yml – Delete Stale Branches

on:
  workflow_dispatch:  # Manual trigger from GitHub UI
  schedule:
    - cron: '0 6 * * 0'

permissions: 
  contents: read

jobs:
  stale_branches:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      issues: write
    steps:
      - name: Harden the runner (Audit all outbound calls)
        uses: step-security/harden-runner@b09bb98e06d4d774595224525879c09bc6e98c40 # v2.20.1
        with:
          egress-policy: audit

      - name: Stale Branches
        uses: crs-k/stale-branches@138918e25f06d439bf76db5305a591d8a3c03678 # v10.0.0
        with:
            # days-before-delete: 180
            # comment-updates: false
            # max-issues: 20
            tag-committer: true
            stale-branch-label: 'stale branch 🗑️'
            # compare-branches: 'info'
            # branches-filter-regex: '^((?!dependabot))'
            # rate-limit: false
            # pr-check: false
            # dry-run: false
            # ignore-issue-interaction: false
            # include-protected-branches: false
            # include-ruleset-branches: false
            # ignore-commit-messages: ''
            # ignore-committers: ''
